// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolResultSystem.Web.Data;

#nullable disable

namespace SchoolResultSystem.Web.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250923193443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SchoolResultSystem.Web.Models.ClassModel", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.ClassSubjectModel", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT");

                    b.ToTable("ClassSubject");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.ClassTeacherModel", b =>
                {
                    b.Property<int?>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.ToTable("ClassTeacher");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.ExamModel", b =>
                {
                    b.Property<string>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamName")
                        .HasColumnType("TEXT");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.ExamResultModel", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PracticalMark")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TheoryMark")
                        .HasColumnType("TEXT");

                    b.HasKey("ExamId");

                    b.ToTable("ExamResult");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.SchoolInfoModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolInfo");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.SubjectModel", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CrHPractical")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CrHTheory")
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticalFullMark")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheoryFullMark")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubjectCode");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SchoolResultSystem.Web.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passwords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
